export const HandleAddCardActionPointerDown = 'handleAddCardActionPointerDown'
export const HandleBlur = 'handleBlur'
export const HandleCardDescriptionCancelPointerDown =
  'handleCardDescriptionCancelPointerDown'
export const HandleCardLabelPickerPointerDown =
  'handleCardLabelPickerPointerDown'
export const HandleClick = 'handleClick'
export const HandleContextMenu = 'handleContextMenu'
export const HandleDragEnd = 'handleDragEnd'
export const HandleDragLeave = 'handleDragLeave'
export const HandleDragOver = 'handleDragOver'
export const HandleDragStart = 'handleDragStart'
export const HandleDrop = 'handleDrop'
export const HandleFocus = 'handleFocus'
export const HandleImageError = 'handleImageError'
export const HandleInput = 'handleInput'
export const HandleKeyDown = 'handleKeyDown'
export const HandleSashPointerDown = 'handleSashPointerDown'
export const HandleSashPointerMove = 'handleSashPointerMove'
export const HandleSashPointerUp = 'handleSashPointerUp'
export const HandleSubmit = 'handleSubmit'
