export const HandleAddCardActionPointerDown = 'handleAddCardActionPointerDown'
export const HandleBlur = 'handleBlur'
export const HandleCardDescriptionCancelPointerDown =
  'handleCardDescriptionCancelPointerDown'
export const HandleCardLabelPickerPointerDown =
  'handleCardLabelPickerPointerDown'
export const HandleClick = 'handleClick'
export const HandleContextMenu = 'handleContextMenu'
export const HandleDragEnd = 'handleDragEnd'
export const HandleDragLeave = 'handleDragLeave'
export const HandleDragOver = 'handleDragOver'
export const HandleDragStart = 'handleDragStart'
export const HandleDrop = 'handleDrop'
export const HandleFocus = 'handleFocus'
export const HandleImageError = 'handleImageError'
export const HandleInput = 'handleInput'
export const HandleKeyDown = 'handleKeyDown'
export const HandlePointerDown = 'handlePointerDown'
export const HandlePointerMove = 'handlePointerMove'
export const HandlePointerUp = 'handlePointerUp'
export const HandleSubmit = 'handleSubmit'
