import type { TrelloViewState } from './TrelloViewState.ts'
import { getAssetBaseUrl } from './AssetBaseUrl.ts'

export const createInitialState = (): TrelloViewState => {
  return {
    activeSearchQuery: '',
    addingCardLabelId: '',
    addingCardListId: '',
    baseUrl: getAssetBaseUrl(import.meta.url),
    boardBackgroundEnabled: false,
    boardDetail: undefined,
    boardLabels: [],
    boardLabelsLoaded: false,
    boardLabelsLoading: false,
    boards: [],
    cardDetailLoading: false,
    cardLabelPickerOpen: false,
    context: {},
    contextMenuCardId: '',
    contextMenuListId: '',
    coverImageUrls: {},
    credentials: undefined,
    draftApiKey: '',
    draftCardDescription: '',
    draftCardTitle: '',
    draftLabelSearchQuery: '',
    draftListTitles: {},
    draftNewCardTitle: '',
    draftSearchQuery: '',
    draftToken: '',
    draggedCardId: '',
    dragTargetListId: '',
    editingCardDescription: false,
    editingCardTitle: false,
    error: '',
    focusedName: '',
    loading: false,
    movingCardId: '',
    recentBoardViews: [],
    savingCardDetail: false,
    savingNewCard: false,
    searchEnabled: false,
    searchResults: [],
    selectedCardDetail: undefined,
  }
}
